export const REPOS_FETCH_BEGIN = 'REPOS_FETCH_BEGIN';
export const REPOS_FETCH_SUCCESS = 'REPOS_FETCH_SUCCESS';
export const REPOS_FETCH_ERROR = 'REPOS_FETCH_ERROR';

export const USER_FETCH_BEGIN = 'USER_FETCH_BEGIN';
export const USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS';
export const USER_FETCH_ERROR = 'USER_FETCH_ERROR';

export const REPO_FETCH_BEGIN = 'REPO_FETCH_BEGIN';
export const REPO_FETCH_SUCCESS = 'REPO_FETCH_SUCCESS';
export const REPO_FETCH_ERROR = 'REPO_FETCH_ERROR';

export const ISSUES_FETCH_BEGIN = 'ISSUES_FETCH_BEGIN';
export const ISSUES_FETCH_SUCCESS = 'ISSUES_FETCH_SUCCESS';
export const ISSUES_FETCH_ERROR = 'ISSUES_FETCH_ERROR';

export const PULLS_FETCH_BEGIN = 'PULLS_FETCH_BEGIN';
export const PULLS_FETCH_SUCCESS = 'PULLS_FETCH_SUCCESS';
export const PULLS_FETCH_ERROR = 'PULLS_FETCH_ERROR';

export const SEARCH_FETCH_BEGIN = 'SEARCH_FETCH_BEGIN';
export const SEARCH_FETCH_SUCCESS = 'SEARCH_FETCH_SUCCESS';
export const SEARCH_FETCH_ERROR = 'SEARCH_FETCH_ERROR';


